$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        2:{
            items:3
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})